#!/bin/bash
# MIT License
# GUARDIAN — StarkHacks 2026
# Script: identify_arm_cam_ports.sh
# Purpose: identify each connected ARM and CAMERA, ask you which physical role
#          each one is, and WRITE the udev rules straight into ./99-guardian.rules
#          (repo copy only — it does NOT touch /etc). Re-runnable: it rewrites
#          just its own managed block, leaving any hand-added rules intact.
#
# Arms have unique serials -> serial-keyed (robust; survives replug/hub changes).
# Cameras often share/empty serials -> the script detects this and falls back to
# PHYSICAL-PORT keying for them (each cam must then stay in its assigned socket).
#
# After it writes the file, to actually apply it:
#     sudo cp 99-guardian.rules /etc/udev/rules.d/
#     sudo udevadm control --reload-rules && sudo udevadm trigger
#     ls -l /dev/guardian_* /dev/cam_*      # confirm all symlinks resolve
#
# Run this from the folder that holds 99-guardian.rules (e.g. 60_scripts/).

set -u
RULES_FILE="./99-guardian.rules"
BEGIN="# >>> GUARDIAN-AUTO >>>   (generated by identify_arm_cam_ports.sh — edit above/below, not inside)"
END="# <<< GUARDIAN-AUTO <<<"

# ── helpers ─────────────────────────────────────────────────────────────────────
attr()   { udevadm info -a -n "$1" 2>/dev/null | grep -m1 "ATTRS{$2}" | sed 's/.*== *"//; s/".*//'; }
port()   { udevadm info -a -n "$1" 2>/dev/null | grep -m1 'KERNELS=="[0-9]' | sed 's/.*KERNELS== *"//; s/".*//'; }
prop()   { udevadm info -q property -n "$1" 2>/dev/null | grep -m1 "^$2=" | cut -d= -f2; }

ask() {  # ask "$prompt" opt1 opt2 ...  -> echoes chosen option (or "" for skip)
  local prompt="$1"; shift
  local opts=("$@")
  echo "  $prompt" >&2
  local i=1
  for o in "${opts[@]}"; do echo "     [$i] $o" >&2; i=$((i+1)); done
  echo "     [s] skip / not part of GUARDIAN" >&2
  local pick
  read -rp "     choose > " pick </dev/tty
  [[ "$pick" == "s" || -z "$pick" ]] && { echo ""; return; }
  if [[ "$pick" =~ ^[0-9]+$ ]] && (( pick>=1 && pick<=${#opts[@]} )); then
    echo "${opts[$((pick-1))]}"
  else
    echo ""   # unrecognized = skip, safer than writing garbage
  fi
}

ARM_RULES=()
CAM_RULES=()

# ── ARMS ─────────────────────────────────────────────────────────────────────────
echo "========================================================================"
echo "  ARMS  — assign each USB-serial device to a role"
echo "========================================================================"
for dev in /dev/ttyACM* /dev/ttyUSB*; do
  [ -e "$dev" ] || continue
  serial=$(attr "$dev" serial)
  model=$(prop "$dev" ID_MODEL)
  p=$(port "$dev")
  echo ""
  echo "  $dev   serial=${serial:-<none>}   model=${model:-?}   port=${p:-?}"
  if echo "$model" | grep -qi 'jtag\|espressif'; then
    echo "     -> looks like the ESP32 PTZ gimbal (not an arm). Skipping."
    continue
  fi
  if [ -z "$serial" ]; then
    echo "     !! no serial on this device — cannot serial-key it; skipping."
    echo "        (If this is an arm, it must be port-keyed by hand.)"
    continue
  fi
  role=$(ask "Which arm is this?" \
      "guardian_left_follower" "guardian_right_follower" \
      "guardian_left_leader"   "guardian_right_leader")
  [ -z "$role" ] && { echo "     skipped."; continue; }
  ARM_RULES+=("SUBSYSTEM==\"tty\", ATTRS{serial}==\"$serial\", SYMLINK+=\"$role\"")
  echo "     -> $role  (serial-keyed)"
done

# ── CAMERAS ──────────────────────────────────────────────────────────────────────
echo ""
echo "========================================================================"
echo "  CAMERAS — assign each capture node to a role"
echo "========================================================================"
# First pass: gather capture nodes + whether serials are unique.
declare -A SERIAL_COUNT
declare -a CAMS   # "dev|serial|port|mjpg"
for dev in /dev/video*; do
  [ -e "$dev" ] || continue
  base=$(basename "$dev")
  idx=$(cat "/sys/class/video4linux/$base/index" 2>/dev/null || echo 1)
  [ "$idx" = "0" ] || continue            # capture node only
  serial=$(attr "$dev" serial)
  p=$(port "$dev")
  mjpg=$(v4l2-ctl -d "$dev" --list-formats 2>/dev/null | grep -c MJPG)
  CAMS+=("$dev|${serial:-}|${p:-}|${mjpg:-0}")
  key="${serial:-__EMPTY__}"
  SERIAL_COUNT["$key"]=$(( ${SERIAL_COUNT["$key"]:-0} + 1 ))
done

cam_serial_ok=1
for k in "${!SERIAL_COUNT[@]}"; do
  { [ "$k" = "__EMPTY__" ] || [ "${SERIAL_COUNT[$k]}" -gt 1 ]; } && cam_serial_ok=0
done
if [ "$cam_serial_ok" -eq 1 ] && [ "${#CAMS[@]}" -gt 0 ]; then
  echo "  (cameras have UNIQUE serials -> serial-keyed, robust)"
else
  echo "  (cameras share/empty serials -> PORT-keyed; each cam must stay in its socket)"
fi

for entry in "${CAMS[@]}"; do
  IFS='|' read -r dev serial p mjpg <<< "$entry"
  echo ""
  echo "  $dev   serial=${serial:-<empty>}   port=${p:-?}   MJPG=$([ "${mjpg:-0}" -gt 0 ] && echo yes || echo NO)"
  [ "${mjpg:-0}" -gt 0 ] || echo "     !! WARNING: no MJPG on this node — collection/rollout need MJPG."
  role=$(ask "Which camera is this?" "cam_left_wrist" "cam_right_wrist" "cam_overhead")
  [ -z "$role" ] && { echo "     skipped."; continue; }
  if [ "$cam_serial_ok" -eq 1 ]; then
    CAM_RULES+=("SUBSYSTEM==\"video4linux\", ATTRS{serial}==\"$serial\", ATTR{index}==\"0\", SYMLINK+=\"$role\"")
    echo "     -> $role  (serial-keyed)"
  else
    if [ -z "$p" ]; then echo "     !! no port path; skipping."; continue; fi
    CAM_RULES+=("SUBSYSTEM==\"video4linux\", KERNELS==\"$p\", ATTR{index}==\"0\", SYMLINK+=\"$role\"")
    echo "     -> $role  (port-keyed: $p)"
  fi
done

# ── write the managed block into ./99-guardian.rules ─────────────────────────────
if [ "${#ARM_RULES[@]}" -eq 0 ] && [ "${#CAM_RULES[@]}" -eq 0 ]; then
  echo ""
  echo "Nothing assigned — not writing anything."
  exit 0
fi

# preserve anything OUTSIDE our managed block; back up first.
tmp=$(mktemp)
if [ -f "$RULES_FILE" ]; then
  cp "$RULES_FILE" "${RULES_FILE}.bak.$(date +%s)"
  # strip any previous GUARDIAN-AUTO block
  awk -v b="$BEGIN" -v e="$END" '
    $0==b {skip=1} skip && $0==e {skip=0; next} !skip {print}
  ' "$RULES_FILE" > "$tmp"
else
  : > "$tmp"
fi

{
  cat "$tmp"
  echo ""
  echo "$BEGIN"
  echo "# Arms: serial-keyed (robust). Cameras: serial- or port-keyed per detection."
  for r in "${ARM_RULES[@]}"; do echo "$r"; done
  [ "${#CAM_RULES[@]}" -gt 0 ] && echo ""
  for r in "${CAM_RULES[@]}"; do echo "$r"; done
  echo "$END"
} > "$RULES_FILE"
rm -f "$tmp"

echo ""
echo "Wrote $RULES_FILE  (backup saved as ${RULES_FILE}.bak.*)"
echo "To apply:"
echo "  sudo cp 99-guardian.rules /etc/udev/rules.d/"
echo "  sudo udevadm control --reload-rules && sudo udevadm trigger"
echo "  ls -l /dev/guardian_* /dev/cam_*"