serial_bridge_node:
  ros__parameters:
    serial_port_left: /dev/ttyACM0
    serial_port_right: /dev/ttyACM1
    baud_rate: 115200
    serial_timeout: 1.0
    wheel_radius: 0.0748
    wheel_base_length: 0.25
    wheel_base_width: 0.20
    cpr: 175.0
    max_ticks_per_sec: 3000.0  # maps 251 RPM -> 3000 ticks/sec, tune down if too fast
    sim_mode: false

mecanum_kinematics_node:
  ros__parameters:
    wheel_radius: 0.0748
    wheel_base_length: 0.311588
    wheel_base_width: 0.39075
    max_rpm: 150
